### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by rctoris** [sniekum/ar_track_alvar#46]
Just a friendly ping for a potential jade release to help some blocking packages for the upcoming beta.

**Comment by 130s** [comment]
Before making a release into new distro I'd suggest https://github.com/sniekum/ar_track_alvar/issues/42 is taken care of (or at least considered).

**Comment by sniekum** [comment]
My ability to keep up with maintaining this package is severely limited right now and is probably only going to get worse in coming months.  Would either/both of you be willing to taking over some of the maintenance duties, since you are some of the more active community members that use the package?  Let me know if you are, and I'll add you as collaborators.

**Comment by 130s** [comment]
I can join the maintenance to at least review the pull requests and do release work. Running physical tests might depend on the occasions. I think you @sniekum already given me the commit rights.

Since it's already out for Indigo, maybe we want to start out by just releasing from `indigo-devel` branch into Jade (taking back what I said considering sooner release the better)?

**Comment by sniekum** [comment]
That's fine with me.

**Comment by 130s** [comment]
Making a progress. Found that `ar_track_alvar_msgs` is in a separate repository. 

@sniekum can you also add me a write access there?

@wjwwood can you also give me a write access to https://github.com/ros-gbp/ar_track_alvar_msgs-release/ ?

Thanks in advance.

**Comment by wjwwood** [comment]
Done.

**Comment by 130s** [comment]
@sniekum can you also add me a write access at `ar_track_alvar_msgs`? Thx!

**Comment by sniekum** [comment]
It looks like you already have it.  Is it not working?

On Sun, Apr 12, 2015 at 11:41 AM, Isaac I.Y. Saito <notifications@github.com

**Comment by 130s** [comment]
> It looks like you already have it.  Is it not working?

Yeah I see it's working.

**Comment by 130s** [comment]
[Blocked at resource-retriever](https://github.com/ros/robot_model/issues/104) not being released yet.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/8150

**Comment by rctoris** [comment]
Thanks! :+1:
